apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clusters
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: https://github.com/vramk23/testinfra1
    targetRevision: HEAD
    path: infra/clusters/argocd-apps
    helm:
      valueFiles:
      - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: tekton-pipelines
