apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-cluster-base-apps
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: https://github.com/vramk23/testinfra1
    targetRevision: main
    path: apps
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane
