
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: "awsdemo-vault-config"
spec:
  args:
    - --debug
  metadata:
    annotations:
      vault.hashicorp.com/agent-inject: "true"
      vault.hashicorp.com/role: "vault-role-crossplane"
      vault.hashicorp.com/agent-inject-secret-creds.txt: "generic/CloudProvider/9a421c7b-13f8-4c1c-89f5-794e47e9af9b"
      vault.hashicorp.com/agent-inject-template-creds.txt: |
        {{- with secret "generic/CloudProvider/9a421c7b-13f8-4c1c-89f5-794e47e9af9b" -}}
          [default]
          aws_access_key_id="{{ .accessKey }}"
          aws_secret_access_key="{{ .secretKey }}"
        {{- end -}}
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-awsdemo
spec:
  package: "xpkg.upbound.io/crossplane-contrib/provider-aws:v0.33.0"
  controllerConfigRef:
    name: "awsdemo-vault-config"
